import * as stylex from '@stylexjs/stylex';
import {
  colors,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
} from '../design-system/tokens.stylex';

export const styles = stylex.create({
  base: {
    width: '100%',
    minHeight: '100% !important',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '24px',
    padding: '16px',
    backgroundColor: colors.grey100Background,
  },
  header: {
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.headingH6,
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.default,
  },
  searchIcon: {
    fill: colors.grey600,
    cursor: 'pointer',
  },
  column: {
    position: 'relative',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
  },
  labelWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    color: colors.grey600,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text1,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.normal,
    textTransform: 'uppercase',
  },
  trashIcon: {
    cursor: 'pointer',
  },
  tagList: {
    minHeight: '32px',
    width: '100%',
    display: 'flex',
    flexWrap: 'wrap',
    gap: '8px',
  },
  tagWrapper: {
    width: 'calc((100% - 16px) / 3)',
    height: '32px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '6px 10px',
    borderRadius: '8px',
    backgroundColor: colors.grey200,
    transition: 'background-color 0.15s',
    cursor: 'pointer',
  },
  tag: {
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text2,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.big,
  },
  row: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '8px 8px 8px 4px',
    cursor: 'pointer',
  },
  tokenWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  name: {
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text2,
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.big,
  },
  amountWrapper: {
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text2,
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.big,
  },
  amount: {
    color: colors.grey1000,
  },
  currency: {
    color: colors.grey600,
  },
  symbolList: {
    position: 'absolute',
    top: '6px',
    left: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '2px',
    padding: '0 2px',
  },
  symbol: {
    textAlign: 'center',
    transition: 'color 0.15s',
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.caption1,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.small,
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  symbolSelected: {
    color: colors.grey300,
  },
  sm: {
    gap: '8px',
  },
  md: {
    gap: '16px',
  },
});
