import * as stylex from '@stylexjs/stylex';
import {
  colors,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
} from '@/modules/core/design-system/tokens.stylex';

export const styles = stylex.create({
  base: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '8px',
    padding: '16px',
    borderRadius: '16px',
    backgroundColor: colors.grey100Background,
    zIndex: '1',
  },
  label: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    color: colors.grey600,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.caption1,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.small,
  },
  inputWrapper: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  input: {
    outline: 'none',
    border: 'none',
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    '-webkit-box-shadow': 'none',
    '-moz-box-shadow': 'none',
    boxShadow: 'none',
    padding: '0',
    minWidth: '0',
    height: '35px',
    flex: '1',
    color: colors.grey900Text,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.headingH3,
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.default,
    textAlign: 'right',
    '::placeholder': {
      color: colors.grey500Muted,
    },
  },
  fee: {
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text1,
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.normal,
  },
  usdEquivalent: {
    color: colors.grey600,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.caption1,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.small,
  },
});
