import * as stylex from '@stylexjs/stylex';
import {
  colors,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
} from '@/modules/core/design-system/tokens.stylex';

export const styles = stylex.create({
  base: {
    width: '100%',
    minHeight: 'var(--tg-viewport-height)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '24px',
    padding: '8px 16px 0 16px',
    backgroundColor: colors.grey0,
  },
  smallGap: {
    gap: '16px',
  },
  headerWrapper: {
    width: '100%',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  header: {
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.headingH4,
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.default,
  },
  statistics: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    gap: '8px',
  },
  stat: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text1,
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.normal,
  },
  label: {
    color: colors.grey500Muted,
  },
  statValue: {
    color: colors.grey900Text,
  },
  trading: {
    width: '100%',
    position: 'relative',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  rotate: {
    width: '40px',
    height: '40px',
    position: 'absolute',
    top: '50%',
    left: '50%',
    translate: '-50% -50%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: '100px',
    border: '4px solid',
    borderColor: colors.grey0,
    backgroundColor: colors.grey100Background,
    cursor: 'pointer',
  },
  priceWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  price: {
    color: colors.grey800,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text1,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.default,
  },
  savingsWrapper: {
    width: '100%',
    height: '95px',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    borderRadius: '16px',
    backgroundColor: colors.grey100Background,
  },
  savings: {
    width: 'max-content',
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    marginLeft: '16px',
  },
  title: {
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text2,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.big,
    whiteSpace: 'nowrap',
  },
  amount: {
    color: colors.grey900Text,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.headingH3,
    fontWeight: fontWeights.bold,
    lineHeight: lineHeights.default,
    whiteSpace: 'nowrap',
  },
  graphWrapper: {
    height: '100%',
    flex: '1',
    position: 'relative',
    overflow: 'hidden',
  },
  graph: {
    height: '100%',
    position: 'absolute',
    right: '0',
    objectFit: 'cover',
  },
  benefitWrapper: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  benefit: {
    color: colors.grey900Text,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text1,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.normal,
  },
  footer: {
    width: '100%',
    position: 'fixed',
    left: '0',
    bottom: '0',
    padding: '8px 16px 8px 16px',
    display: 'flex',
    flexDirection: 'column',
    gap: '26px',
    backgroundColor: colors.grey0,
  },
  bottomGap: {
    paddingBottom: '22px',
  },
  percentGroup: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '0 6px',
  },
  percent: {
    cursor: 'pointer',
    margin: '0px',
    outline: 'none',
    border: 'none',
    flex: '1',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    gap: '4px',
    padding: '8px',
    borderRadius: '40px',
    backgroundColor: {
      default: colors.grey100Background,
      ":is([data-state='on'])": colors.grey200,
    },
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.caption1,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.small,
    transition: 'all 0.15s',
  },
  percentValue: {
    color: colors.grey900Text,
  },
  sign: {
    color: colors.grey600,
  },
});
