export const Endpoints = {
  EMAIL_PASSWORD: '/auth/email',
  GOOGLE_OAUTH: '/auth/google/oauth',
  TWITTER_OAUTH: '/auth/twitter2/oauth',
  FACEBOOK_OAUTH: '/auth/facebook/oauth',
  OAUTH_LOGIN: '/auth/tokens',
  WALLET_AUTH: '/auth/wallet',
  LOGOUT: '/auth/private/logout',
  REFRESH_TOKEN: '/auth/refresh',
  EMAIL_EXISTS: '/auth/exists',
  PROFILE: '/private/profile',
  BALANCES: '/private/balances',
  CUSTODIAL_WALLET: '/private/wallet',
  WITHDRAW: '/private/withdraw',
  SWAP: '/private/swap',
  NETWORKS: '/networks',
  TOKENS: '/tokens',
  SYSTEM_RATES: '/system-rates',
  TRANSACTIONS: '/private/transactions',
  BALANCE_CHART: '/private/balance/chart',
  PROFIT_CHART: '/private/profit',
  ASSET_SUMMARY: '/private/asset/summary',
  ASSET_CHART: '/private/asset/chart',
  ASSET_PRICE: '/price',
  ASSET_PRICE_CHANGE: '/price-change',
};
