import * as stylex from '@stylexjs/stylex';
import { animations } from '@/modules/core/design-system/animations.stylex';
import {
  colors,
  fontFamilies,
  fontSizes,
  fontWeights,
  lineHeights,
  shadows,
} from '@/modules/core/design-system/tokens.stylex';

export const styles = stylex.create({
  base: {
    position: 'fixed',
    height: '80px',
    bottom: '0',
    left: '0',
    right: '0',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 16px 24px',
    cursor: 'pointer',
    backgroundColor: colors.grey0,
    borderRadius: '12px 12px 0 0',
    boxShadow: shadows.dropShadow,
  },
  infoWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  info: {
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
  },
  label: {
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text1,
    fontWeight: fontWeights.normal,
    lineHeight: lineHeights.normal,
  },
  priceWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.text2,
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.big,
  },
  chart: {
    width: 'auto',
    height: '100%',
  },
  chevronUpIcon: {
    width: '24px',
    height: '24px',
    fill: colors.grey600,
  },
  overlay: {
    position: 'fixed',
    inset: '0',
  },
  dialog: {
    position: 'fixed',
    top: '100%',
    left: '0',
    right: '0',
    zIndex: '1',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    padding: '0 16px 24px',
    overflow: 'auto',
    borderRadius: '12px 12px 0px 0px',
    backgroundColor: colors.grey0,
    boxShadow: shadows.dropShadow,
    outline: {
      default: null,
      ':focus': 'none',
    },
  },
  headerWrapper: {
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    padding: '16px 0 16px 24px',
  },
  header: {
    margin: '0 auto',
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontSize: fontSizes.headingH6,
    fontWeight: fontWeights.medium,
    lineHeight: lineHeights.default,
  },
  close: {
    cursor: 'pointer',
    margin: '0px',
    padding: '0px',
    border: 'none',
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  priceInfo: {
    margin: '0',
    padding: '0',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    gap: '4px',
    color: colors.grey1000,
    fontFamily: fontFamilies.roobertPro,
    fontWeight: fontWeights.medium,
  },
  price: {
    fontSize: fontSizes.headingH5,
    lineHeight: lineHeights.default,
  },
  change: {
    fontSize: fontSizes.text2,
    lineHeight: lineHeights.big,
  },
  appear: {
    animationName: animations.appear,
    animationDuration: '0.3s',
    animationFillMode: 'forwards',
  },
  hide: {
    animationName: animations.hide,
    animationDuration: '0.3s',
    animationFillMode: 'forwards',
  },
});
